services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trading-observer-frontend
    restart: always
    ports:
      - "3000:3000"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - WS_PORT=3001
      - NEXT_PUBLIC_WS_URL=http://localhost:3001
    env_file:
      - .env
    volumes:
      - ./users.json:/app/users.json
      - ./watchlists.json:/app/watchlists.json
      - ./public/uploads:/app/public/uploads
    command: node server.js

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trading-observer-backend
    restart: always
    ports:
      - "3001:3001"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - NODE_ENV=production
      - PORT=3001
    env_file:
      - .env
    volumes:
      - ./settings.json:/app/settings.json
      - ./users.json:/app/users.json
      - ./watchlists.json:/app/watchlists.json
      - ./public/uploads:/app/public/uploads
    command: node server/index.mjs

networks:
  default:
    driver: bridge
